### ISSUE TITLE
Adding row/column buttons

### ISSUE THREAD

**Issue by paulderaadt** [Tearth/Bitboard-Viewer#2]
Hi Tearth,

I've forked a version where I added a button to each row and column that fills the respective col/row when clicked. Makes it easy to get the magic numbers for file and rank masks.

Is this something you would be interested in adding to your project? My CSS skills are nonexistent so I don't really know how to align the buttons with the checkboxes in a neat way.

![afbeelding](https://user-images.githubusercontent.com/22319443/185940184-4fc06176-ced3-4455-8327-0b97dc8294b4.png)

**Comment by Tearth** [comment]
Hi @paulderaadt, this looks great! I'm far from being competent in CSS too, but I can try to align these buttons with the rest of the checkboxes - please make a pull request, so I will take a look at it in my free time.

**Comment by Tearth** [comment]
Finally got a bit of time: I've merged changes and did a few tweaks to align new buttons - still not perfect, but I think it's good enough. Thank you for your contribution!
