### ISSUE TITLE
Bug with shift left when bit is at max index

### ISSUE THREAD

**Issue by valentinringlet** [Tearth/Bitboard-Viewer#4]
First of all, thanks a lot for making this tool, it has been extremely helpful this far

I found a small bug:
When the current value has the bit as the most significant index set (e.g. 0x8000000000000000) and you click on the Shift Left button, the values will actually not be reset to zero, but it's as if that bit is kept (e.g. shifting 0x8000000000000000 left by one results in 0x10000000000000000, which is more than a 64-bit unsigned value can hold). 

Further pressing "shift left" will continue increasing the number. It is only reset once the "1" bit would re-enter the range of the first 64 bits.

Note: I feel like this could simply be fixed by checking if the value becomes larger or equal to 2^64, and if so, reset all values to zero. Not sure but worth a try

**Comment by Tearth** [comment]
Hi, thanks for the report, indeed this should be rather easy to fix so I will try to implement it tomorrow.

**Comment by Tearth** [comment]
Fixed in the latest PR thanks to @EliasKramer - thank you!
